### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by ajthinking** [ajthinking/archetype#23]
This package does not yet support PHP 8 features. Would love some help with this

**Comment by pkeogan** [comment]
@ajthinking just spent my day adding `php 8.0` features and finishing your `->add()->trait([...])` functions, added features also to reproduce `findOrCreate` related functionality.  also added some automatic `phpunit feature` testing functions. Also added function to sort the `use` /`trait` statements by length. Also added formatters to clean up laravel based code to go over existing code to match @taylorotwell preferred visually coding methods. 

![image](https://user-images.githubusercontent.com/30511153/132966957-58eda15d-6146-4f47-b62b-5d909f648fff.png)
_All the above code was generated with `PHPFile::`_

I would make a PR , but my code does not follow your project structure at all, and breaks its nice formatting/setup. Ive done quite a bit of method chaining based packages, but you took it to another level. I am always interesting in learning new ways, and if your willing to explain it to me a little over VoIP I can conform the changes, otherwise I plan on branching off from your ` v0.2.5` release.

**Comment by ajthinking** [comment]
Thanks for taking a look at this 👍  Would love to merge it and assist with any questions. Im available today preferably or weekday evenings ECT

**Comment by pkeogan** [comment]
Got caught up with a project past few days, I'll send you an email to try and setup something next week.

**Comment by ajthinking** [comment]
@pkeogan, could you share the branch? Would love to see it

**Comment by lukas-frey** [comment]
Is this actually completed? I can't seem to find a way to add traits using PHPFile.

EDIT: I managed to add a trait using `ASTBuilder` / `BuilderFactory`, like this:
```php
$builder->class()->insertStmt((new BuilderFactory())->useTrait('HasRoles')->getNode())
```

however not using the defined endpoints like there are for implements, extends, etc.

I fear I'm not experienced enough to make a PR to add the endpoint though.

**Comment by ajthinking** [comment]
Hi @LukasFreyCZ , thanks for bumping and nice work around.
It was never merged, so we are still missing some things related to traits.
I will try to take a look at it this weekend, will ping you if/when there is a release

**Comment by lukas-frey** [comment]
> Hi @LukasFreyCZ , thanks for bumping and nice work around.
> It was never merged, so we are still missing some things related to traits.
> I will try to take a look at it this weekend, will ping you if/when there is a release

Sounds great, thanks! If you need some help, feel free to message/tag me and I'll try my best. :) Even if it's just for testing.
