### ISSUE TITLE
How to add methods?

### ISSUE THREAD

**Issue by ekosynth** [ajthinking/archetype#79]
Hi, when using PHPFile, is there a way to add methods to a class?

**Comment by ajthinking** [comment]
Hi,
you could do it like this:

```php
use PhpParser\BuilderFactory;

PHPFile::load(App\Dummy::class)
  ->astQuery()
  ->class()
  ->insertStmt(
	  (new BuilderFactory)->method('myMethod')->getNode()
  )
  ->commit()
  ->end()
```

See details on how to use BuilderFactory [here](https://github.com/nikic/PHP-Parser/blob/master/doc/component/AST_builders.markdown).

As an alternative, it is also possible to provide a snippets file, and extract the method body from that. This can be useful if the method is long since constructing the AST with the BuilderFactory can get quite cumbersome. [This technique is used internally when adding relationship methods to LaravelFiles](https://github.com/ajthinking/archetype/blob/cfee02623c784da8ac4004803efed99fc56ead18/src/Endpoints/Laravel/HasMany.php#L23)
